export enum Skills {
    acrobatics = "acrobatics",
    animalHandling = "animalHandling",
    arcana = "arcana",
    athletics = "athletics",
    deception = "deception",
    history = "history",
    insight = "insight",
    intimidation = "intimidation",
    investigation = "investigation",
    medicine = "medicine",
    nature = "nature",
    perception = "perception",
    performance = "performance",
    persuasion = "persuasion",
    religion = "religion",
    sleightOfHand = "sleightOfHand",
    stelth = "stelth",
    survival = "survival"
}